version: "3.8"

services:
  backend:
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    environment:
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: noreply@example.com
    depends_on:
      mailcatcher:
        condition: service_started

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped